from enum import Enum

class SearchType(Enum):
    ONE_LINE_ADDRESS = "onelineaddress"
    ADDRESS          = "address"
    COORDINATES      = "coordinates"



class Benchmark(Enum):
    CURRENT     = "Public_AR_Current"
    ACS_2018    = "Public_AR_ACS2018"
    CENSUS_2010 = "Public_AR_Census2010"



class AncestoryCode(Enum):
    ALSATIAN        =   "001"
    ANDORRAN        =   "002"
    AUSTRIAN        =   "003"
    TIROL           =   "004"
    BASQUE          =   "005"
    FRENCH_BASQUE   =   "006"
    SPANISH_BASQUE  =   "007"
    BELGIAN         =   "008"
    FLEMISH         =   "009"
    WALLOON             =   "010"
    BRITISH             =   "011"
    BRITISH_ISLES       =   "012"
    CHANNEL_ISLANDER    =   "013"
    GIBRALTARIAN        =   "014"
    CORNISH             =   "015"
    CORSICAN =   "016"
    CYPRIOT =   "017"
    GREEK_CYPRIOT =   "018"
    TURKISH_CYPRIOT =   "019"
    DANISH =   "020"
    DUTCH =   "021"
    ENGLISH =   "022"
    FAROE_ISLANDER =   "023"
    FINNISH =   "024"
    KARELIAN =   "025"
    FRENCH =   "026"
    LORRAINIAN =   "027"
    BRETON =   "028"
    FRISIAN =   "029"
    FRIULIAN =   "030"
    LADIN =   "031"
    GERMAN =   "032"
    BAVARIAN =   "033"
    BERLINER =   "034"
    HAMBURGER =   "035"
    HANNOVER =   "036"
    HESSIAN =   "037"
    LUBECKER =   "038"
    POMERANIAN =   "039"
    PRUSSIAN =   "040"
    SAXON =   "041"
    SUDETENLANDER =   "042"
    WESTPHALIAN         =   "043"
    EAST_GERMAN         =   "044"
    WEST_GERMAN         =   "045"
    GREEK               =   "046"
    CRETAN              =   "047"
    CYCLADIC_ISLANDER   =   "048"
    ICELANDER           =   "049"
    IRISH               =   "050"
    ITALIAN             =   "051"
    TRIESTE             =   "052"
    ABRUZZI             =   "053"
    APULIAN             =   "054"
    BASILICATA          =   "055"
    CALABRIAN           =   "056"
    AMALFIAN        =   "057"
    EMILIA_ROMAGNA  =   "058"
    ROMAN           =   "059"
    LIGURIAN        =   "060"
    LOMBARDIAN      =   "061"
    MARCHE          =   "062"
    MOLISE          =   "063"
    NEAPOLITAN      =   "064"
    PIEDMONTESE     =   "065"
    PUGLIA          =   "066"
    SARDINIAN       =   "067"
    SICILIAN        =   "068"
    TUSCAN          =   "069"
    TRENTINO        =   "070"
    UMBRIAN         =   "071"
    VALLE_DAOSTA    =   "072"
    VENETIAN        =   "073"
    SAN_MARINO      =   "074"
    LAPP            =   "075"
    LIECHTENSTEINER =   "076"
    LUXEMBOURGER    =   "077"
    MALTESE         =   "078"
    MANX            =   "079"
    MONEGASQUE      =   "080"
    NORTH_IRISH     =   "081"
    NORWEGIAN       =   "082"
    OCCITAN         =   "083"
    PORTUGUESE      =   "084"
    AZORES_ISLANDER =   "085"
    MADEIRAN        =   "086"
    SCOTCH_IRISH    =   "087"
    SCOTTISH        =   "088"
    SWEDISH         =   "089"
    ALAND_ISLANDER  =   "090"
    SWISS           =   "091"
    SUISSE          =   "092"
    SWITZER         =   "093"
    IRISH_SCOTCH    =   "094"
    ROMANSCH        =   "095"
    SUISSE_ROMANDE  =   "096"
    WELSH           =   "097"
    SCANDINAVIAN    =   "098"
    CELTIC          =   "099"